---
title: "TFM UOC"
output: html_document
date: '2022-03-25'
---

## Hide warnings:

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

## Logistic regression with glm

Data & param:

```{r}
# Imports:
library(caret)
source("./codes/cohen_kappa_fun.R")
source("./codes/CI_MinimumSampleSize_fun.R")
source("./codes/fit_acc_fun.R")
# Data:
require(ISLR)
attach(Smarket) # attach allows you to look up in R variables within a dataframe
```

```{r}
# Predictor:
X <- Smarket[-ncol(Smarket)]
# Predict:
Y <- Smarket[ncol(Smarket)]
Y <- unlist(Y)
```

```{r}
source("./codes/logistic_regression_fun.R")
```

```{r}
system.time(
MinSizeLogReg <- minimum_sample_logistic(X,Y,p_vec=1:99/100,thr_acc=0.95)
)
MinSizeLogReg
```

## Logistic regression with train.

```{r}
# Imports:
library(caret)
source("./codes/cohen_kappa_fun.R")
source("./codes/CI_MinimumSampleSize_fun.R")
source("./codes/fit_acc_fun.R")
# Data:
require(ISLR)
attach(Smarket) # attach allows you to look up in R variables within a dataframe
```

```{r}
# Predictor:
X <- Smarket[-ncol(Smarket)]
# Predict:
Y <- Smarket[ncol(Smarket)]
Y <- unlist(Y)
```

```{r}
source("./codes/logistic_regression_fun_v2.R")
```

```{r}
system.time(
minimum_sample_logistic_v2(X,Y,p_vec = 1:99/100, thr_acc = 0.95)
)
```

## Logistic regression with train, and parallelization.

```{r}
# Imports:
library(caret)
library(foreach)
source("./codes/cohen_kappa_fun.R")
source("./codes/CI_MinimumSampleSize_fun.R")
source("./codes/fit_acc_fun.R")
# Data:
require(ISLR)
attach(Smarket) # attach allows you to look up in R variables within a dataframe
```

```{r}
# Predictor:
X <- Smarket[-ncol(Smarket)]
# Predict:
Y <- Smarket[ncol(Smarket)]
Y <- unlist(Y)
```

```{r}
source("./codes/logistic_regression_fun_v2_parallel.R")
```

```{r}
system.time(
minimum_sample_logistic_v2_parallel(X,Y,p_vec = 1:99/100, thr_acc = 0.95, n.cores = 8)
)
```

## Random Forest, sequential.

```{r}
# Imports:
library(caret)
source("./codes/cohen_kappa_fun.R")
source("./codes/CI_MinimumSampleSize_fun.R")
source("./codes/fit_acc_fun.R")
# Data:
require(ISLR)
attach(Smarket) # attach allows you to look up in R variables within a dataframe
```

```{r}
# Predictor:
X <- Smarket[-ncol(Smarket)]
# Predict:
Y <- Smarket[ncol(Smarket)]
Y <- unlist(Y)
```

```{r}
source("./codes/rf_fun.R")
```

```{r}
system.time(
minimum_sample_rf(X = X, Y = Y,
                  p_vec = 1:99/100,
                  thr_acc = 0.95)
)
```

## Random forest, paralelization

```{r}
# Imports:
library(caret)
library(foreach)
source("./codes/cohen_kappa_fun.R")
source("./codes/CI_MinimumSampleSize_fun.R")
source("./codes/fit_acc_fun.R")
# Data:
require(ISLR)
attach(Smarket) # attach allows you to look up in R variables within a dataframe
```

```{r}
# Predictor:
X <- Smarket[-ncol(Smarket)]
# Predict:
Y <- Smarket[ncol(Smarket)]
Y <- unlist(Y)
```

```{r}
source("./codes/rf_fun_parallel.R")
```

```{r}
system.time(
minimum_sample_rf_parallel(X = X, Y = Y,
                  p_vec = 1:99/100,
                  thr_acc = 0.95,
                  n.cores = 12)
)
```

## Naive Bayes, paralelization

```{r}
# Imports:
library(caret)
library(foreach)
source("./codes/cohen_kappa_fun.R")
source("./codes/CI_MinimumSampleSize_fun.R")
source("./codes/fit_acc_fun.R")
# Data:
require(ISLR)
attach(Smarket) # attach allows you to look up in R variables within a dataframe
```

```{r}
# Predictor:
X <- Smarket[-ncol(Smarket)]
# Predict:
Y <- Smarket[ncol(Smarket)]
Y <- unlist(Y)
```

```{r}
source("./codes/nb_fun_parallel.R")
```

```{r}
system.time(
minimum_sample_naivebayes(X = X, Y = Y,
                  p_vec = 1:99/100,
                  thr_acc = 0.95,
                  n.cores = 1)
)
```

## kNN

```{r}
# Imports:
library(caret)
library(foreach)
source("./codes/cohen_kappa_fun.R")
source("./codes/CI_MinimumSampleSize_fun.R")
source("./codes/fit_acc_fun.R")
# Data:
# require(ISLR)
# attach(Smarket) # attach allows you to look up in R variables within a dataframe
```

```{r}
# # Predictor:
# X <- Smarket[-ncol(Smarket)]
# # Predict:
# Y <- Smarket[ncol(Smarket)]
# Y <- unlist(Y)
```

```{r}
# Wisconsin breast cancer data:
wbcd <- read.csv("./data/classification/wisc_bc_data.csv", 
                 stringsAsFactors = FALSE)
# id column provides no info, so we remove it:
wbcd <- wbcd[-1]

# label diagnosis column:
wbcd$diagnosis<- factor(wbcd$diagnosis, 
                        levels = c("B", "M"),
                        labels = c("Benign", "Malignant")
                        )

# Function for normalization:
normalize <- function(x) {
return ((x - min(x)) / (max(x) - min(x)))
}

# create new df with normalized numerical columns:
wbcd_n <- as.data.frame(lapply(wbcd[2:31], normalize))
```

```{r}
# Variable to predict:
Y_wbcd <- wbcd[,1]
# Variables to use as predictors:
X_wbcd <- wbcd_n
```


```{r}
source("./codes/knn_fun_parallel.R")
```

```{r}
system.time(
minimum_sample_knn(X = X_wbcd, Y = Y_wbcd,
                  p_vec = 1:99/100,
                  thr_acc = 0.95,
                  n.cores = 1)
)
```
